# Generated by Django 5.0.7 on 2024-08-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='bundle',
            name='last_updated',
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterapp.bundle')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
