# Generated by Django 5.0.7 on 2024-08-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0002_remove_bundle_counter_remove_bundle_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
