# Generated by Django 5.0.7 on 2024-08-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0003_alter_counter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
