# Generated by Django 5.0.7 on 2024-08-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0004_alter_counter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField()),
                ('link', models.CharField(max_length=300)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counterapp.bundle')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
